In [2]:
import pandas as pd #Pandas for data manipulation
import numpy as np  # Numpy for numerical computing as well as feature engineering

In [3]:

# Load the datasets, Pandas converts it into DataFrames (row, columns, Headings)
movies = pd.read_csv(r"E:\end-to-end-collaborative-filtering-recommendation-system\data\movies.csv")
ratings = pd.read_csv(r"E:\end-to-end-collaborative-filtering-recommendation-system\data\ratings.csv")
tags = pd.read_csv(r"E:\end-to-end-collaborative-filtering-recommendation-system\data\tags.csv")
links = pd.read_csv(r"E:\end-to-end-collaborative-filtering-recommendation-system\data\links.csv")

In [4]:
# Head to get the top 5 rows from the data
movies.head()

,movieId,title,genres,Primary Genre
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure
1,2,Jumanji (1995),Adventure|Children|Fantasy,Adventure
2,3,Grumpier Old Men (1995),Comedy|Romance,Comedy
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy
4,5,Father of the Bride Part II (1995),Comedy,Comedy

In [5]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [12]:
print(movies.shape)
print("####################################")
print(ratings.shape)

(9742, 4)
####################################
(100836, 4)

In [13]:
movies.columns

Index(['movieId', 'title', 'genres', 'Primary Genre'], dtype='object')

In [16]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [17]:
movies.info

<bound method DataFrame.info of       movieId                                      title  \
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

                                           genres Primary Genre
0     Adventure|Animation|Children|Comedy|Fantasy     Adventure
1                      Adventure|Children|Fantasy     Adventure
2                                  Comedy|Romance        Comedy
3                            Comedy|Drama|Romance        Comedy
4                                          Comedy        Comedy
...                                           ...           ...
9737              Action|Animation|Comedy|Fantasy        Action
9738                     Animation|Comedy|Fantasy     Animation
9739                                        Drama         Drama
9740                             Action|Animation        Action
9741                                       Comedy        Comedy

[9742 rows x 4 columns]>

In [18]:
ratings.info

<bound method DataFrame.info of         userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]>