This notebook contains the analysis of the movies.csv dataset

In [2]:
import pandas as pd

In [3]:
#Loading the dataset
movies = pd.read_csv(r"E:\end-to-end-collaborative-filtering-recommendation-system\data\movies.csv")

In [5]:
#Basic Info
movies.head()

,movieId,title,genres,Primary Genre
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure
1,2,Jumanji (1995),Adventure|Children|Fantasy,Adventure
2,3,Grumpier Old Men (1995),Comedy|Romance,Comedy
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy
4,5,Father of the Bride Part II (1995),Comedy,Comedy

In [6]:
movies.tail()

,movieId,title,genres,Primary Genre
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,Action
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,Animation
9739,193585,Flint (2017),Drama,Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,Action
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,Comedy

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movieId        9742 non-null   int64
 1   title          9742 non-null   object
 2   genres         9742 non-null   object
 3   Primary Genre  9742 non-null   object
dtypes: int64(1), object(3)
memory usage: 304.6+ KB

In [12]:
movies.columns

Index(['movieId', 'title', 'genres', 'Primary Genre'], dtype='object')

In [13]:
movies.shape

(9742, 4)

In [14]:
movies.describe(include="all")

              movieId            title genres Primary Genre
count     9742.000000             9742   9742          9742
unique            NaN             9737    951            19
top               NaN  Saturn 3 (1980)  Drama        Comedy
freq              NaN                2   1053          2779
mean     42200.353623              NaN    NaN           NaN
std      52160.494854              NaN    NaN           NaN
min          1.000000              NaN    NaN           NaN
25%       3248.250000              NaN    NaN           NaN
50%       7300.000000              NaN    NaN           NaN
75%      76232.000000              NaN    NaN           NaN
max     193609.000000              NaN    NaN           NaN

In [ ]:
movies.isnull().sum() #Check missing rows

movieId          0
title            0
genres           0
Primary Genre    0
dtype: int64

In [ ]:
movies.duplicated().sum() #Check duplicates

np.int64(0)

In [26]:
movies['movieId'].nunique()

9742

In [27]:
movies['genres'].head()

0    Adventure|Animation|Children|Comedy|Fantasy
1                     Adventure|Children|Fantasy
2                                 Comedy|Romance
3                           Comedy|Drama|Romance
4                                         Comedy
Name: genres, dtype: object